### ISSUE TITLE
在Antd 5.2.2(其他版本没有查）中,没有找到antd.css

### ISSUE THREAD

**Issue by sjbwylbs** [neoddish/antv-site-demo-rc#13]
https://github.com/neoddish/antv-site-demo-rc/blob/d4cd2ea06c381cd6f8e58dc772701bbc4c05bdc5/src/LintCard/index.tsx#L1

**Comment by neoddish** [comment]
这个组件库是纯粹给 AVA 官网 demo 简化代码使用的，目前并没有升级 antd 5 的需求，所以不支持 antd 5 哈。
